---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: stocks
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 10
  kafkaClusterRef:
    name: kafka
    namespace: confluent
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: stocks-new
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 10
  kafkaClusterRef:
    name: kafka
    namespace: confluent
---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: stocks-connector
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: "stocks"
    quickstart: "stock_trades"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schemas.enable: "true"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    max.interval: "1000"
    iterations: "1000000"
